### PR TITLE
Rybla Combinators

### PR DESCRIPTION
**Pull request by freckletonj**
I like the PR @rybla made at https://github.com/neurallambda/arc-like/pull/2, currently a WIP.

In order for me to contribute to that effort, I've made a branch `rybla-combinators` directly on this repo. I'm going to close that PR without merging, and make this PR of the same commits against `master` (major thank you :pray: ) but where I can now contribute too. @rybla if you'd like to change anything, you could make PRs against `rybla-combinators` from your repo, would this be convenient for you, or something else?

### CODE REVIEW

**Comment by freckletonj** [comment]
I was finding the OO paradigm a little confusing to contribute to, so refactored to a functional paradigm which matches my aesthetic and I think is a bit simpler (latest commit, https://github.com/neurallambda/arc-like/pull/3/commits/76f039dd05d41eaad8362fe8f9e3dbda25d6ce9e).

I just haven't added random puzzles (eg https://github.com/neurallambda/arc-like/pull/3/files#diff-71f5eb90ad8e3721e6015c3570840a457fae35e6aa44fce0f112f5479e56ecfaR292) yet, but otherwise this has feature parity with your work.

Thoughts, a reasonable second pass?

**Comment by rybla** [comment]
Cool! I can look more closely later

**Comment by freckletonj** [comment]
I'm mid refactor and will finish tonight, but just wanted to let you know.

The refactor redefines combinators as being functions over `(inputs, outputs)`, ie `(inputs, outputs) -> (inputs, outputs)`. This allows swapping them for instance, which is important for a denoising puzzle, where the puzzle input is a noised version of a block, and the output is the denoised version. I'll explain later if that doesnt make sense. I've got a couple more things in mind too, should be done and pushed up in the next 12 hours.

**Comment by freckletonj** [comment]
Refactor's done, and I've added a few more puzzles.

**Comment by freckletonj** [comment]
Current state of affairs:

image

Now I think we just need to fix up the rest of the repo to cut over to this version permanently, :scissors: the old code.

**Comment by freckletonj** [comment]
Thanks again @rybla , I'm deleting the old `puzzles.py` in favor of this, merged!

**Pull request merged**
